server:
  port: 8081

management:
  endpoints:
    web:
      base-path: /v1/employee/actuator
      exposure:
        include: info, health, loggers
  health:
    redis:
      enabled: false

spring:
  profiles.active: local-1
  application:
    name: employee-service
  datasource:
    url: jdbc:postgresql://localhost:5433/employee_db
    username: employee
    password: employee
    hikari:
      maximum-pool-size: 10
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase: #liquibase changelog properties
    enabled: true
    change-log: classpath:db/db-changelog-master.yaml
#  mvc:
#    pathmatch:
#      matching-strategy: ant-path-matcher
publishDate: